// GENERATED by scripts/gen-starter-images.ts — do not edit by hand.
//
// Where the printed art of each ST-01/ST-02 card lives upstream, read from the
// pinned punk-records commit 2a48b092cf4c77acbe22367b8334bbc75102c702.
//
// This package ships no images and never will: `scripts/download-card-images.ts`
// fetches them into a gitignored directory under the client, by hand. See the
// scope note in the root README.
import type { CardId } from '@optcg/engine';

export const STARTER_IMAGE_URLS: Readonly<Record<CardId, string>> = Object.freeze({
  "ST01-001": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-001.png?260731",
  "ST01-002": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-002.png?260731",
  "ST01-003": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-003.png?260731",
  "ST01-004": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-004.png?260731",
  "ST01-005": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-005.png?260731",
  "ST01-006": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-006.png?260731",
  "ST01-007": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-007.png?260731",
  "ST01-008": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-008.png?260731",
  "ST01-009": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-009.png?260731",
  "ST01-010": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-010.png?260731",
  "ST01-011": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-011.png?260731",
  "ST01-012": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-012.png?260731",
  "ST01-013": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-013.png?260731",
  "ST01-014": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-014.png?260731",
  "ST01-015": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-015.png?260731",
  "ST01-016": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-016.png?260731",
  "ST01-017": "https://en.onepiece-cardgame.com/images/cardlist/card/ST01-017.png?260731",
  "ST02-001": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-001.png?260731",
  "ST02-002": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-002.png?260731",
  "ST02-003": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-003.png?260731",
  "ST02-004": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-004.png?260731",
  "ST02-005": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-005.png?260731",
  "ST02-006": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-006.png?260731",
  "ST02-007": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-007.png?260731",
  "ST02-008": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-008.png?260731",
  "ST02-009": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-009.png?260731",
  "ST02-010": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-010.png?260731",
  "ST02-011": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-011.png?260731",
  "ST02-012": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-012.png?260731",
  "ST02-013": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-013.png?260731",
  "ST02-014": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-014.png?260731",
  "ST02-015": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-015.png?260731",
  "ST02-016": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-016.png?260731",
  "ST02-017": "https://en.onepiece-cardgame.com/images/cardlist/card/ST02-017.png?260731"
});
