// GENERATED by scripts/gen-starters.ts — do not edit by hand.
//
// The printed data for the ST-01 and ST-02 cards, as a module rather than a
// file read, so the browser client can register them without `node:fs`.
// `tests/starters.test.ts` pins this against data/cards.en.json, and
// `tests/spanish.test.ts` pins STARTER_TEXT_ES against data/cards.es.json.
import type { Decklist, EnglishCardDefinition } from './types.js';
import type { SpanishText } from './spanish-types.js';

export const STARTER_CARDS: readonly EnglishCardDefinition[] = [
  {
    "cardId": "ST01-001",
    "name": "Monkey.D.Luffy",
    "category": "leader",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 0,
    "power": 5000,
    "counter": null,
    "life": 5,
    "keywords": [],
    "types": [
      "Supernovas",
      "Straw Hat Crew"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "[Activate: Main] [Once Per Turn] Give this Leader or 1 of your Characters up to 1 rested DON!! card.",
    "triggerText": null
  },
  {
    "cardId": "ST01-002",
    "name": "Usopp",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 2,
    "power": 2000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Straw Hat Crew"
    ],
    "attributes": [
      "Ranged"
    ],
    "effectText": "[DON!! x2] [When Attacking] Your opponent cannot activate a [Blocker] Character that has 5000 or more power during this battle.",
    "triggerText": "[Trigger] Play this card."
  },
  {
    "cardId": "ST01-003",
    "name": "Karoo",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 1,
    "power": 3000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Animal",
      "Alabasta"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "-",
    "triggerText": null
  },
  {
    "cardId": "ST01-004",
    "name": "Sanji",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 2,
    "power": 4000,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Straw Hat Crew"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "[DON!! x2] This Character gains [Rush].<br>(This card can attack on the turn in which it is played.)",
    "triggerText": null
  },
  {
    "cardId": "ST01-005",
    "name": "Jinbe",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 3,
    "power": 5000,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Fish-Man",
      "Straw Hat Crew"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "[DON!! x1] [When Attacking] Up to 1 of your Leader or Character cards other than this card gains +1000 power during this turn.",
    "triggerText": null
  },
  {
    "cardId": "ST01-006",
    "name": "Tony Tony.Chopper",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 1,
    "power": 1000,
    "counter": null,
    "life": 0,
    "keywords": [
      "Blocker"
    ],
    "types": [
      "Animal",
      "Straw Hat Crew"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "triggerText": null
  },
  {
    "cardId": "ST01-007",
    "name": "Nami",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 1,
    "power": 1000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Straw Hat Crew"
    ],
    "attributes": [
      "Special"
    ],
    "effectText": "[Activate: Main] [Once Per Turn] Give up to 1 rested DON!! card to your Leader or 1 of your Characters.",
    "triggerText": null
  },
  {
    "cardId": "ST01-008",
    "name": "Nico Robin",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 3,
    "power": 5000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Straw Hat Crew"
    ],
    "attributes": [
      "Wisdom"
    ],
    "effectText": "-",
    "triggerText": null
  },
  {
    "cardId": "ST01-009",
    "name": "Nefeltari Vivi",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 2,
    "power": 4000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Alabasta"
    ],
    "attributes": [
      "Slash"
    ],
    "effectText": "-",
    "triggerText": null
  },
  {
    "cardId": "ST01-010",
    "name": "Franky",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 4,
    "power": 6000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Straw Hat Crew"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "-",
    "triggerText": null
  },
  {
    "cardId": "ST01-011",
    "name": "Brook",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 2,
    "power": 3000,
    "counter": 2000,
    "life": 0,
    "keywords": [],
    "types": [
      "Straw Hat Crew"
    ],
    "attributes": [
      "Slash"
    ],
    "effectText": "[On Play] Give up to 2 rested DON!! cards to your Leader or 1 of your Characters.",
    "triggerText": null
  },
  {
    "cardId": "ST01-012",
    "name": "Monkey.D.Luffy",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 5,
    "power": 6000,
    "counter": null,
    "life": 0,
    "keywords": [
      "Rush"
    ],
    "types": [
      "Supernovas",
      "Straw Hat Crew"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "[Rush] (This card can attack on the turn in which it is played.)<br>[DON!! x2] [When Attacking] Your opponent cannot activate [Blocker] during this battle.",
    "triggerText": null
  },
  {
    "cardId": "ST01-013",
    "name": "Roronoa Zoro",
    "category": "character",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 3,
    "power": 5000,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Straw Hat Crew"
    ],
    "attributes": [
      "Slash"
    ],
    "effectText": "[DON!! x1] This Character gains +1000 power.",
    "triggerText": null
  },
  {
    "cardId": "ST01-014",
    "name": "Guard Point",
    "category": "event",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 1,
    "power": 0,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Animal",
      "Straw Hat Crew"
    ],
    "attributes": [],
    "effectText": "[Counter] Up to 1 of your Leader or Character cards gains +3000 power during this battle.",
    "triggerText": "[Trigger] Up to 1 of your Leader or Character cards gains +1000 power during this turn."
  },
  {
    "cardId": "ST01-015",
    "name": "Gum-Gum Jet Pistol",
    "category": "event",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 4,
    "power": 0,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Straw Hat Crew"
    ],
    "attributes": [],
    "effectText": "[Main] K.O. up to 1 of your opponent's Characters with 6000 power or less.",
    "triggerText": "[Trigger] Activate this card's [Main] effect."
  },
  {
    "cardId": "ST01-016",
    "name": "Diable Jambe",
    "category": "event",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 1,
    "power": 0,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Straw Hat Crew"
    ],
    "attributes": [],
    "effectText": "[Main] Select up to 1 of your {Straw Hat Crew} type Leader or Character cards. Your opponent cannot activate [Blocker] if that Leader or Character attacks during this turn.",
    "triggerText": "[Trigger] K.O. up to 1 of your opponent's [Blocker] Characters with a cost of 3 or less."
  },
  {
    "cardId": "ST01-017",
    "name": "Thousand Sunny",
    "category": "stage",
    "color": "red",
    "colors": [
      "red"
    ],
    "cost": 2,
    "power": 0,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Straw Hat Crew"
    ],
    "attributes": [],
    "effectText": "[Activate: Main] You may rest this Stage: Up to 1 {Straw Hat Crew} type Leader or Character card on your field gains +1000 power during this turn.",
    "triggerText": null
  },
  {
    "cardId": "ST02-001",
    "name": "Eustass\"Captain\"Kid",
    "category": "leader",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 0,
    "power": 5000,
    "counter": null,
    "life": 5,
    "keywords": [],
    "types": [
      "Supernovas",
      "Kid Pirates"
    ],
    "attributes": [
      "Special"
    ],
    "effectText": "[Activate: Main] [Once Per Turn]  ③ (You may rest the specified number of DON!! cards in your cost area.) You may trash 1 card from your hand: Set this Leader as active.",
    "triggerText": null
  },
  {
    "cardId": "ST02-002",
    "name": "Vito",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 3,
    "power": 5000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Firetank Pirates"
    ],
    "attributes": [
      "Ranged"
    ],
    "effectText": "-",
    "triggerText": null
  },
  {
    "cardId": "ST02-003",
    "name": "Urouge",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 2,
    "power": 3000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Fallen Monk Pirates"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "[DON!! x1] If you have 3 or more Characters, this card gains +2000 power.",
    "triggerText": null
  },
  {
    "cardId": "ST02-004",
    "name": "Capone\"Gang\"Bege",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 1,
    "power": 1000,
    "counter": null,
    "life": 0,
    "keywords": [
      "Blocker"
    ],
    "types": [
      "Supernovas",
      "Firetank Pirates"
    ],
    "attributes": [
      "Special"
    ],
    "effectText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
    "triggerText": null
  },
  {
    "cardId": "ST02-005",
    "name": "Killer",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 3,
    "power": 3000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Kid Pirates"
    ],
    "attributes": [
      "Slash"
    ],
    "effectText": "[On Play] K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.",
    "triggerText": "[Trigger] Play this card."
  },
  {
    "cardId": "ST02-006",
    "name": "Koby",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 4,
    "power": 6000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Navy"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "-",
    "triggerText": null
  },
  {
    "cardId": "ST02-007",
    "name": "Jewelry Bonney",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 1,
    "power": 1000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Bonney Pirates"
    ],
    "attributes": [
      "Special"
    ],
    "effectText": "[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Character: Look at 5 cards from the top of your deck; reveal up to 1 {Supernovas} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
    "triggerText": null
  },
  {
    "cardId": "ST02-008",
    "name": "Scratchmen Apoo",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 2,
    "power": 3000,
    "counter": 2000,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "On-Air Pirates"
    ],
    "attributes": [
      "Ranged"
    ],
    "effectText": "[DON!! x1] [When Attacking] Rest up to 1 of your opponent's DON!! cards.",
    "triggerText": null
  },
  {
    "cardId": "ST02-009",
    "name": "Trafalgar Law",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 5,
    "power": 6000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Heart Pirates"
    ],
    "attributes": [
      "Slash"
    ],
    "effectText": "[On Play] Set up to 1 of your {Supernovas} or {Heart Pirates} type rested Characters with a cost of 5 or less as active.",
    "triggerText": null
  },
  {
    "cardId": "ST02-010",
    "name": "Basil Hawkins",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 5,
    "power": 6000,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Hawkins Pirates"
    ],
    "attributes": [
      "Slash"
    ],
    "effectText": "[DON!! x1] [Once Per Turn] [Your Turn] If this Character battles your opponent's Character, set this card as active.",
    "triggerText": null
  },
  {
    "cardId": "ST02-011",
    "name": "Heat",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 2,
    "power": 4000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Kid Pirates"
    ],
    "attributes": [
      "Special"
    ],
    "effectText": "-",
    "triggerText": null
  },
  {
    "cardId": "ST02-012",
    "name": "Bepo",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 1,
    "power": 3000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Minks",
      "Heart Pirates"
    ],
    "attributes": [
      "Strike"
    ],
    "effectText": "-",
    "triggerText": null
  },
  {
    "cardId": "ST02-013",
    "name": "Eustass\"Captain\"Kid",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 7,
    "power": 7000,
    "counter": null,
    "life": 0,
    "keywords": [
      "Blocker"
    ],
    "types": [
      "Supernovas",
      "Kid Pirates"
    ],
    "attributes": [
      "Special"
    ],
    "effectText": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)<br>[DON!! x1] [End of Your Turn] Set this Character as active.",
    "triggerText": null
  },
  {
    "cardId": "ST02-014",
    "name": "X.Drake",
    "category": "character",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 4,
    "power": 5000,
    "counter": 1000,
    "life": 0,
    "keywords": [],
    "types": [
      "Navy",
      "Supernovas",
      "Drake Pirates"
    ],
    "attributes": [
      "Slash"
    ],
    "effectText": "[DON!! x1] [Your Turn] If this Character is rested, your {Supernovas} or {Navy} type Leaders and Characters gain +1000 power.",
    "triggerText": null
  },
  {
    "cardId": "ST02-015",
    "name": "Scalpel",
    "category": "event",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 1,
    "power": 0,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Heart Pirates"
    ],
    "attributes": [],
    "effectText": "[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, set up to 1 of your DON!! cards as active.",
    "triggerText": "[Trigger] Set up to 2 of your DON!! cards as active."
  },
  {
    "cardId": "ST02-016",
    "name": "Repel",
    "category": "event",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 2,
    "power": 0,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Kid Pirates"
    ],
    "attributes": [],
    "effectText": "[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, set up to 1 of your DON!! cards as active.",
    "triggerText": null
  },
  {
    "cardId": "ST02-017",
    "name": "Straw Sword",
    "category": "event",
    "color": "green",
    "colors": [
      "green"
    ],
    "cost": 2,
    "power": 0,
    "counter": null,
    "life": 0,
    "keywords": [],
    "types": [
      "Supernovas",
      "Hawkins Pirates"
    ],
    "attributes": [],
    "effectText": "[Main] Rest up to 1 of your opponent's Characters.",
    "triggerText": "[Trigger] Play up to 1 {Supernovas} type card with a cost of 2 or less from your hand."
  }
];

export const STARTER_DECKLISTS: readonly Decklist[] = [
  {
    "id": "ST-01",
    "name": "Straw Hat Crew",
    "packId": "569001",
    "leader": "ST01-001",
    "cards": [
      {
        "cardId": "ST01-002",
        "qty": 4
      },
      {
        "cardId": "ST01-003",
        "qty": 4
      },
      {
        "cardId": "ST01-004",
        "qty": 4
      },
      {
        "cardId": "ST01-005",
        "qty": 4
      },
      {
        "cardId": "ST01-006",
        "qty": 4
      },
      {
        "cardId": "ST01-007",
        "qty": 4
      },
      {
        "cardId": "ST01-008",
        "qty": 4
      },
      {
        "cardId": "ST01-009",
        "qty": 4
      },
      {
        "cardId": "ST01-010",
        "qty": 4
      },
      {
        "cardId": "ST01-011",
        "qty": 2
      },
      {
        "cardId": "ST01-012",
        "qty": 2
      },
      {
        "cardId": "ST01-013",
        "qty": 2
      },
      {
        "cardId": "ST01-014",
        "qty": 2
      },
      {
        "cardId": "ST01-015",
        "qty": 2
      },
      {
        "cardId": "ST01-016",
        "qty": 2
      },
      {
        "cardId": "ST01-017",
        "qty": 2
      }
    ]
  },
  {
    "id": "ST-02",
    "name": "Worst Generation",
    "packId": "569002",
    "leader": "ST02-001",
    "cards": [
      {
        "cardId": "ST02-002",
        "qty": 4
      },
      {
        "cardId": "ST02-003",
        "qty": 2
      },
      {
        "cardId": "ST02-004",
        "qty": 4
      },
      {
        "cardId": "ST02-005",
        "qty": 2
      },
      {
        "cardId": "ST02-006",
        "qty": 4
      },
      {
        "cardId": "ST02-007",
        "qty": 4
      },
      {
        "cardId": "ST02-008",
        "qty": 4
      },
      {
        "cardId": "ST02-009",
        "qty": 2
      },
      {
        "cardId": "ST02-010",
        "qty": 2
      },
      {
        "cardId": "ST02-011",
        "qty": 4
      },
      {
        "cardId": "ST02-012",
        "qty": 4
      },
      {
        "cardId": "ST02-013",
        "qty": 2
      },
      {
        "cardId": "ST02-014",
        "qty": 4
      },
      {
        "cardId": "ST02-015",
        "qty": 2
      },
      {
        "cardId": "ST02-016",
        "qty": 4
      },
      {
        "cardId": "ST02-017",
        "qty": 2
      }
    ]
  }
];

/** The Spanish printed text for the same 34 cards. Presentation only. */
export const STARTER_TEXT_ES: Readonly<Record<string, SpanishText>> = {
  "ST01-001": {
    "effectText": "[Activar: Principal] [Una Vez por Turno] Dale a este Líder o a 1 de tus Personajes hasta 1 carta DON!! agotada.",
    "triggerText": null
  },
  "ST01-002": {
    "effectText": "[DON!! x2] [Al Atacar] Tu rival no puede activar un Personaje con [Bloqueador] que tenga 5000 de poder o más durante este combate.",
    "triggerText": "[Disparador] Juega esta carta."
  },
  "ST01-003": {
    "effectText": "-",
    "triggerText": null
  },
  "ST01-004": {
    "effectText": "[DON!! x2] Este Personaje gana [Rush].<br>(Esta carta puede atacar en el turno en que se juega.)",
    "triggerText": null
  },
  "ST01-005": {
    "effectText": "[DON!! x1] [Al Atacar] Hasta 1 de tus cartas de Líder o Personaje que no sea esta carta gana +1000 de poder durante este turno.",
    "triggerText": null
  },
  "ST01-006": {
    "effectText": "[Bloqueador] (Después de que tu rival declare un ataque, puedes agotar esta carta para convertirla en el nuevo objetivo del ataque.)",
    "triggerText": null
  },
  "ST01-007": {
    "effectText": "[Activar: Principal] [Una Vez por Turno] Dale hasta 1 carta DON!! agotada a tu Líder o a 1 de tus Personajes.",
    "triggerText": null
  },
  "ST01-008": {
    "effectText": "-",
    "triggerText": null
  },
  "ST01-009": {
    "effectText": "-",
    "triggerText": null
  },
  "ST01-010": {
    "effectText": "-",
    "triggerText": null
  },
  "ST01-011": {
    "effectText": "[Al Jugar] Dale hasta 2 cartas DON!! agotadas a tu Líder o a 1 de tus Personajes.",
    "triggerText": null
  },
  "ST01-012": {
    "effectText": "[Rush] (Esta carta puede atacar en el turno en que se juega.)<br>[DON!! x2] [Al Atacar] Tu rival no puede activar [Bloqueador] durante este combate.",
    "triggerText": null
  },
  "ST01-013": {
    "effectText": "[DON!! x1] Este Personaje gana +1000 de poder.",
    "triggerText": null
  },
  "ST01-014": {
    "effectText": "[Contraataque] Hasta 1 de tus cartas de Líder o Personaje gana +3000 de poder durante este combate.",
    "triggerText": "[Disparador] Hasta 1 de tus cartas de Líder o Personaje gana +1000 de poder durante este turno."
  },
  "ST01-015": {
    "effectText": "[Principal] Deja K.O. hasta 1 Personaje de tu rival con 6000 de poder o menos.",
    "triggerText": "[Disparador] Activa el efecto [Principal] de esta carta."
  },
  "ST01-016": {
    "effectText": "[Principal] Selecciona hasta 1 de tus cartas de Líder o Personaje de tipo {Straw Hat Crew}. Tu rival no puede activar [Bloqueador] si ese Líder o Personaje ataca durante este turno.",
    "triggerText": "[Disparador] Deja K.O. hasta 1 Personaje con [Bloqueador] de tu rival con un coste de 3 o menos."
  },
  "ST01-017": {
    "effectText": "[Activar: Principal] Puedes agotar este Escenario: Hasta 1 carta de Líder o Personaje de tipo {Straw Hat Crew} en tu campo gana +1000 de poder durante este turno.",
    "triggerText": null
  },
  "ST02-001": {
    "effectText": "[Activar: Principal] [Una Vez por Turno]  ③ (Puedes agotar esa cantidad de cartas DON!! de tu área de coste.) Puedes descartar 1 carta de tu mano: Pon este Líder como activo.",
    "triggerText": null
  },
  "ST02-002": {
    "effectText": "-",
    "triggerText": null
  },
  "ST02-003": {
    "effectText": "[DON!! x1] Si tienes 3 o más Personajes, esta carta gana +2000 de poder.",
    "triggerText": null
  },
  "ST02-004": {
    "effectText": "[Bloqueador] (Después de que tu rival declare un ataque, puedes agotar esta carta para convertirla en el nuevo objetivo del ataque.)",
    "triggerText": null
  },
  "ST02-005": {
    "effectText": "[Al Jugar] Deja K.O. hasta 1 Personaje agotado de tu rival con un coste de 3 o menos.",
    "triggerText": "[Disparador] Juega esta carta."
  },
  "ST02-006": {
    "effectText": "-",
    "triggerText": null
  },
  "ST02-007": {
    "effectText": "[Activar: Principal] ➀ (Puedes agotar esa cantidad de cartas DON!! de tu área de coste.) Puedes agotar este Personaje: Mira 5 cartas del tope de tu mazo; revela hasta 1 carta de tipo {Supernovas} y agrégala a tu mano. Después, pon el resto en el fondo de tu mazo en el orden que quieras.",
    "triggerText": null
  },
  "ST02-008": {
    "effectText": "[DON!! x1] [Al Atacar] Agota hasta 1 carta DON!! de tu rival.",
    "triggerText": null
  },
  "ST02-009": {
    "effectText": "[Al Jugar] Pon hasta 1 de tus Personajes agotados de tipo {Supernovas} o {Heart Pirates} con un coste de 5 o menos como activo.",
    "triggerText": null
  },
  "ST02-010": {
    "effectText": "[DON!! x1] [Una Vez por Turno] [Tu Turno] Si este Personaje combate contra un Personaje de tu rival, pon esta carta como activa.",
    "triggerText": null
  },
  "ST02-011": {
    "effectText": "-",
    "triggerText": null
  },
  "ST02-012": {
    "effectText": "-",
    "triggerText": null
  },
  "ST02-013": {
    "effectText": "[Bloqueador] (Después de que tu rival declare un ataque, puedes agotar esta carta para convertirla en el nuevo objetivo del ataque.)<br>[DON!! x1] [Fin de Tu Turno] Pon este Personaje como activo.",
    "triggerText": null
  },
  "ST02-014": {
    "effectText": "[DON!! x1] [Tu Turno] Si este Personaje está agotado, tus Líderes y Personajes de tipo {Supernovas} o {Navy} ganan +1000 de poder.",
    "triggerText": null
  },
  "ST02-015": {
    "effectText": "[Contraataque] Hasta 1 de tus cartas de Líder o Personaje gana +2000 de poder durante este combate. Después, pon hasta 1 de tus cartas DON!! como activa.",
    "triggerText": "[Disparador] Pon hasta 2 de tus cartas DON!! como activas."
  },
  "ST02-016": {
    "effectText": "[Contraataque] Hasta 1 de tus cartas de Líder o Personaje gana +4000 de poder durante este combate. Después, pon hasta 1 de tus cartas DON!! como activa.",
    "triggerText": null
  },
  "ST02-017": {
    "effectText": "[Principal] Agota hasta 1 Personaje de tu rival.",
    "triggerText": "[Disparador] Juega hasta 1 carta de tipo {Supernovas} con un coste de 2 o menos de tu mano."
  }
};
