/**
 * Regenerates `src/starterImages.generated.ts` from the pinned upstream dataset.
 *
 * Run by hand — never from build, never from test:
 *
 *     pnpm --filter @optcg/cards run gen:starter-images
 *
 * Why the URLs come from upstream rather than from a template: the real record
 * carries a version query (`ST01-001.png?260731`), and nothing here knows
 * whether it is optional. Building `.../card/<id>.png` by hand would be a guess
 * about somebody else's cache-busting scheme. The dataset knows; ask it.
 *
 * Same pin as `ingest.ts` — the same commit SHA, so an upstream regeneration
 * cannot silently change what this writes. Unlike `ingest.ts` this fetches the
 * 34 per-card files directly instead of the repository tarball: the tarball
 * exists there to get two sources in one request, and here there is only one.
 *
 * `img_url` was dropped by the ingest on purpose, and that stays true —
 * `CardDefinition` gains nothing. An image address is presentation, not a rule,
 * so it lives in its own module keyed by card id.
 *
 * Requires Node >= 22.6 for TypeScript type stripping, and network access.
 */
import { writeFileSync } from 'node:fs';
import { STARTER_DECKLISTS } from '../dist/starters.generated.js';

const SOURCE_REPO = 'buhbbl/punk-records';
const SOURCE_COMMIT = '2a48b092cf4c77acbe22367b8334bbc75102c702';

interface SourceCard {
  id: string;
  /** Absolute, with the version query. `img_url` is the relative twin. */
  img_full_url: string;
}

function rawUrl(packId: string, cardId: string): string {
  return `https://raw.githubusercontent.com/${SOURCE_REPO}/${SOURCE_COMMIT}/english/cards/${packId}/${cardId}.json`;
}

/** Every card of both starter decks, Leader included, with its pack id. */
function starterCardIds(): { cardId: string; packId: string }[] {
  const out: { cardId: string; packId: string }[] = [];
  const seen = new Set<string>();
  for (const deck of STARTER_DECKLISTS) {
    for (const cardId of [deck.leader, ...deck.cards.map((entry) => entry.cardId)]) {
      if (seen.has(cardId)) continue;
      seen.add(cardId);
      out.push({ cardId, packId: deck.packId });
    }
  }
  return out.sort((a, b) => a.cardId.localeCompare(b.cardId));
}

async function main(): Promise<void> {
  const cards = starterCardIds();
  process.stdout.write(`Resolving ${cards.length} image addresses at ${SOURCE_COMMIT}\n`);

  const urls: Record<string, string> = {};
  for (const { cardId, packId } of cards) {
    const response = await fetch(rawUrl(packId, cardId));
    if (!response.ok) {
      throw new Error(`${cardId}: ${response.status} ${response.statusText}`);
    }
    const card = (await response.json()) as SourceCard;
    if (card.id !== cardId) {
      throw new Error(`${cardId}: the record identifies itself as ${card.id}`);
    }
    if (typeof card.img_full_url !== 'string' || card.img_full_url === '') {
      throw new Error(`${cardId}: no img_full_url in the source record`);
    }
    urls[cardId] = card.img_full_url;
  }

  const body = `// GENERATED by scripts/gen-starter-images.ts — do not edit by hand.
//
// Where the printed art of each ST-01/ST-02 card lives upstream, read from the
// pinned punk-records commit ${SOURCE_COMMIT}.
//
// This package ships no images and never will: \`scripts/download-card-images.ts\`
// fetches them into a gitignored directory under the client, by hand. See the
// scope note in the root README.
import type { CardId } from '@optcg/engine';

export const STARTER_IMAGE_URLS: Readonly<Record<CardId, string>> = Object.freeze(${JSON.stringify(
    urls,
    null,
    2,
  )});
`;

  writeFileSync(new URL('../src/starterImages.generated.ts', import.meta.url), body, 'utf8');
  process.stdout.write(`wrote ${Object.keys(urls).length} addresses\n`);
}

await main();
