/**
 * Regenerates `src/starters.generated.ts` from the committed card data.
 *
 * Why a generated module instead of reading the JSON at runtime: the client is
 * a browser bundle, and `cards.ts` loads `data/cards.en.json` with
 * `node:fs` — 1.5 MB of data, deliberately read from disk rather than imported,
 * for reasons that are entirely right on Node and entirely unavailable in a
 * bundler. Shipping the whole set through a JSON import would put 1.5 MB in the
 * bundle to use 34 cards of it.
 *
 * So the two starter decks get their printed data emitted as a plain module,
 * committed, and pinned by `tests/starters.test.ts` against the same JSON this
 * script reads. Drift is a failing test, not a silent divergence.
 *
 * Abilities are deliberately NOT baked in: they are code, they live in
 * `abilities.ts`, and `registerStarterCards()` attaches them the same way
 * `cards.ts` does for the full set.
 *
 * Reads the package's own `dist` rather than `src`: the sources import each
 * other with `.js` specifiers, which Node's type stripping cannot resolve back
 * to `.ts`. Build first.
 *
 *   pnpm --filter @optcg/cards run build
 *   pnpm --filter @optcg/cards run gen:starters
 */
import { writeFileSync } from 'node:fs';
import { englishCards } from '../dist/cards.js';
import { ST01_DECK, ST02_DECK } from '../dist/decklists.js';
import type { EnglishCardDefinition } from '../dist/types.js';

const decks = [ST01_DECK, ST02_DECK];
const needed = new Set<string>();
for (const deck of decks) {
  needed.add(deck.leader);
  for (const entry of deck.cards) {
    needed.add(entry.cardId);
  }
}

const cards: EnglishCardDefinition[] = englishCards
  .filter((card) => needed.has(card.cardId))
  // `abilities` comes from code and must not be frozen into the data module.
  .map(({ abilities: _abilities, ...printed }) => printed as EnglishCardDefinition)
  .sort((a, b) => a.cardId.localeCompare(b.cardId));

if (cards.length !== needed.size) {
  const missing = [...needed].filter((id) => !cards.some((card) => card.cardId === id));
  throw new Error(`cards missing from the set: ${missing.join(', ')}`);
}

const header = `// GENERATED by scripts/gen-starters.ts — do not edit by hand.
//
// The printed data for the ST-01 and ST-02 cards, as a module rather than a
// file read, so the browser client can register them without \`node:fs\`.
// \`tests/starters.test.ts\` pins this against data/cards.en.json.
import type { Decklist, EnglishCardDefinition } from './types.js';

export const STARTER_CARDS: readonly EnglishCardDefinition[] = `;

const body = `${JSON.stringify(cards, null, 2)};

export const STARTER_DECKLISTS: readonly Decklist[] = ${JSON.stringify(decks, null, 2)};
`;

writeFileSync(new URL('../src/starters.generated.ts', import.meta.url), header + body, 'utf8');
console.log(`wrote ${cards.length} cards and ${decks.length} decklists`);
